language: generic
sudo: required

branches:
  only:
    - master

notifications:
  email: false
  
services:
  - docker

before_install:
  - docker build -t rollingstone80/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rollingstone80/docker-react yarn test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-662886091518"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
