language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t rollingstone80/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rollingstone80/docker-react yarn test